### ISSUE TITLE
Reuse of Royal Society manifests

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#20]
Manifest 1 from Royal society: https://digirati-co-uk.github.io/rs-ingest/iiif-wip/PT_73_9_17.json

Manifest 2 from Royal Society: https://digirati-co-uk.github.io/rs-ingest/iiif-wip/PT_73_9_18.json
both drawings by: https://www.wikidata.org/wiki/Q3296150
Mary Buckland
British paleontologist, marine biologist and scientific illustrator

Maybe we could add Mary Buckland to the database and then drop these manifests into Mirador?

**Comment by kennethsn** [comment]
Confirming that @emulatingkat Added these to story:
sciencestories.io/Q3296150
