### ISSUE TITLE
Women in Science Bibliography

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#21]
Let's create a page (maybe even link to it from the nav bar for our Women in Science bibliography as seen here: https://www.wikidata.org/wiki/User:YULdigitalpreservation/ScienceStories/WomenInScienceBibliography

Here is the link to the SPARQL query: https://github.com/ScienceStories/SPARQL/blob/master/womenInScienceBib.rq

**Comment by kennethsn** [comment]
See http://sciencestories.ksn.io/bibliography
