### ISSUE TITLE
Multiple manifests in a moment only displays first

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#31]
For http://sciencestories.io/Q265353 two manifests were added to the Mirador moment, but it looks like only one shows up.

**Comment by kennethsn** [comment]
This is actually accounted for in the builder! (Forgot to tell you how + poor labeling in the form) 
In the builder, when selecting the mirador layout type, look for 'layout dimensions'. This is written in by default as '1x1', but change it to '1x2' and republish.  I will put a better description under the labels; in hind-sight just saying 'layout dimensions' is not that intuitive haha.  [Closing issue for now, but feel free to re-open if it persists]
