### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#34]
Could we discuss a process for deletion if we make a mistake?

I made a mistake here: http://sciencestories.io/Q15814059 The manifest in the Mirador moment does not correspond with this science story.

**Comment by kennethsn** [comment]
No worries! Go to the story, and click the edit button next to the favorite, this will take you to a pre-populated builder screen with the current status of the story. Click the little trashcan icon at the bottom right corner of each mirador window that you'd like to delete and re-publish. (Every time you hit publish as well, we save a back-up of the json so you never lose the status if an over-write/edit goes wrong as well, so you can't break anything haha)  [Closing issue for now, but feel free to re-open]
