### ISSUE TITLE
Previewing content from external sources

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#37]
Would it be possible to preview content from an external source on the "Learn More" slide type?

I'm thinking about [http://sciencestories.io/Q34091#5](url)

If a person is unfamiliar with CSPAN, it might be helpful to preview a couple of the videos from: [https://www.c-span.org/person/?maejemison](url).

Perhaps we should pull the description of the source from the property description of the external id to display on hover if people want to read more.

**Comment by kennethsn** [comment]
Implemented property description and iframe!
