### ISSUE TITLE
Authors who have a lot of publications have very busy timelines

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#46]
We may want to consider creating additional views for timelines to support different publication frequency patterns.
I noticed that this timeline is very full:
http://www.sciencestories.io/Q19630838#2

**Comment by kennethsn** [comment]
Fixed with  e5b0178 by skipping "author" statements in the timeline. This will help declutter the timeline and makes since to skip since we have the library slide dedicated to publications. Great catch!
