### ISSUE TITLE
Add DOI info to items on library shelf

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#60]
We could use P356 to provide a DOI (if available) for works on a story's library shelf. This would allow the reader to click to find the work.

**Comment by kennethsn** [comment]
Just added support for DOI in fd8f008!
Now, the library shelf links waterfall in the following order:
"DOI" -> "Handle" (P1184) -> "Full Work Available At" -> "Official Website" -> Link to Wikidata item
