### ISSUE TITLE
Some IIIF content duplicated

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#63]
See: http://www.sciencestories.io/Q4981402#2 

The slides have different metadata.

Is it possible that one of these was created via story builder and one came in from another interaction?

**Comment by kennethsn** [comment]
That's exactly what happened! 

Based on this commit: https://github.com/ScienceStories/application/commit/a48371

In our story generation sparql query, we capture the property for IIIF manifest (P6108) to autogenerate mirador slides if this manifest is in Wikidata and this time we got a hit for the same one that was added manually! (https://www.wikidata.org/wiki/Q43220353)

For reference of the query: 
https://github.com/ScienceStories/application/blob/92e7c7bd35e5b9af6bed9975645448684b62e7bb/server/controllers/sparql.js#L70-L73

I can now remove the manual slide!
