### ISSUE TITLE
video demo

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#85]
Consider creating a short video to provide an overview of SS.

**Comment by emulatingkat** [comment]
Some inspiration videos:
 [WarSampo 2017 winner ](https://vimeo.com/212249404)
  [Dive+ 2017 winner](https://www.youtube.com/watch?v=FI3MPiU9rjo)
   [sushi inspiration video for text usage]( https://www.pbssocal.org/programs/chefsteps/chefsteps-secrets-perfect-sushi-rice/)

**Comment by kennethsn** [comment]
https://www.youtube.com/watch?v=_xMjPB0b0IQ
