### ISSUE TITLE
Consider supporting video

### ISSUE THREAD

**Issue by emulatingkat** [ScienceStories/application#99]
In the story http://www.sciencestories.io/Q19873335 we would like to be able to display the video linked via P10. This really cool site has more info about the video format: https://wikidp.org/Q309440

**Comment by emulatingkat** [comment]
I was working in the story builder and I saw that video is already supported! I see that this is referenced in #81, so I won't close this. Thanks for already supporting this. Confirming that it already supports .webm, the video has been added to this story.

**Comment by kennethsn** [comment]
Funny enough, I saw this as an opportunity to make an automated one using the P10 prop! It'll be really easy since we have the layout built for the manual moment, so definitely worth it!

**Comment by kennethsn** [comment]
Added in 2.0 powered by the Stories Service 🎉
